### ISSUE TITLE
SEVIRI geolocation may be incorrect

### ISSUE THREAD

**Issue by simonrp84** [ORAC-CC/orac#23]
Prior to December 2017, SEVIRI data contained a small shift in the geolocation relative to the idealised GEOS projection. See this for more information: https://github.com/pytroll/satpy/wiki/SEVIRI-georeferencing-offset-correction

Currently, ORAC does not account for this shift. This means that all data prior to 12/2017 has incorrect pixel lat/lon + angles.
A fix should be applied. Preferably the same one used by satpy, as shown in the document above.

**Comment by danielphilipp** [comment]
As I also noticed this issue I implemented a shift correction to the SEVIRI reading library locally (https://github.com/gmcgarragh/seviri_util). This correction should be called if the file parameter "TypeOfEarthModel=1" (see MSG Level 1.5 Image Data Format Description, p. 22). 

The fix could be easily implemented in the seviri_util/nav_util.c module using the intermediate coordinates which are calculated anyways to transform from image coordiantes to geographical coordinates (see https://cgms-info.org/documents/pdf_cgms_03.pdf, p. 20). 

As the intermediate coordinates (x and y) are basically just the scanning angle, we can convert them to km simply by multiplying them with the satellite altitude h (see https://proj.org/operations/projections/geos.html). Now we can correct for the 1.5 km offset and re-transform them to intermediate coordinates for further processing. Could look like the following:

```
const double a = 6378.1690;
const double offset = 1.5;

if((int)earthmod == 1 {
   /* Satellite altitude: Distance_from_earth_centre - equatorial_radius */
   alt = h - a;

   /* Transform x and y (intermeidate coordiantes/scanning angle) from degrees to km and apply 
   offset */
    x_m = (x * alt) - offset;
    y_m = (y * alt) + offset;

    /* Re-transform from modified meters to degrees to obtain the shifted values */
    x = (x_m / alt);
    y = (y_m / alt);
}
...
```
First testing gave the same results as satpy for a SEVIRI test slot but I will add some further testing within the next days.

**Comment by simonrp84** [comment]
Cool, that sounds great. Thanks for looking into this! Happy to give the code a test when you're happy with it.

**Comment by danielphilipp** [comment]
I did some testing and validation today. I found a little mistake in the code snippet posted above:

`x_m = (x * alt) - offset;`

should be

`x_m = (x * alt) + offset;`

See the zipped html file for the test results (2015/11/14 1200 slot):
[seviri_util_grid_correction_test.zip](https://github.com/ORAC-CC/orac/files/4650889/seviri_util_grid_correction_test.zip)

So basically the math is working as it should I think. Surprisingly I have some issue with the "TypeOfEarthModel" parameter which should either be 1 or 2 according to EUMETSAT. From my HRIT file, seviri_util found "TypeOfEarthModel" to be 0. Satpy does also not apply the correction even though it should as the scene is before December 2017. I'm not sure what exactly is happening here maybe the files are corrupt or the files stored at the ECMWF archive are too old so that the parameter has not been introduced back then. I will test another one tomorrow.

**Comment by simonrp84** [comment]
I have some old seviri data direct from the Eumetsat archive, will check the earth model in that tomorrow!

**Comment by danielphilipp** [comment]
Okay I misinterpreted the "georef_offset_corrected" attribute in the satpy dataset. False means that the offset is not corrected in the HRIT file and has to be corrected by satpy. I first thought the other way around. However I think there is a bug in the seviri_util reading routine for the GeometricProcessing header because I cannot print values for all parameters in this header. All of them (e.g. EquatorialRaidus, NorthPolarRadius) are 0 so likely not read correctly.

**Comment by simonrp84** [comment]
Yes, I have noticed that. I think I have a fix on my local copy of the library, will check later today.

**Comment by simonrp84** [comment]
Fix for the `GeometricProcessing` header now committed to the `seviri_util` library!

**Comment by danielphilipp** [comment]
SEVIRI georeferencing offset correction now commited to the seviri_util library!

**Comment by simonrp84** [comment]
Thanks for making the fix, Daniel! I'll close this bug report now.
