### ISSUE TITLE
Emissivity file

### ISSUE THREAD

**Issue by pdebuyl** [ORAC-CC/orac#92]
Hello all,

Sorry for coming back with a similar request: I can't find the global emissivity files :-/

> ERROR) Could not locate /data/pdebuyl/ORAC_DATA/modis_emis: global_emis_inf10_monthFilled_MYD11C3.AXXXX%j.*nc

I downloaded all that I could from the NWPSAF website. The link https://lpdaac.usgs.gov/dataset_discovery/modis/modis_products_table/mcd43c1_v006/ is dead and those "global_emis_inf10" files seem really hard to find.

I tried to use `--use-modis-emis` but that won't work either.

>  Get surface emissivity
>  <<<<<<<<<<<<<<< Entering get_surface_emissivity()
>  cyear: 2023
>  cdoy: 237
>  cimss emis_path: None
>  assume_full_path:  T
>  nland:      7381565
>  n channels for land emissivity:            3
>  instrument bands for land emissivity:            4           9          10
>  instument wavelengths for land emissivity:    3.92000008       10.8000002       12.0000000    
>  cimss_emis_path_file: None
>  <<<<<<<<<<<<<<< Entering read_cimss_emissivity()
>  path_to_file: None
>  wavelengths:    3.92000008       10.8000002       12.0000000    
>  ERROR: ncdf_open(): read_cimss_emissivity(): Error opening file None
>  No such file or directory
> STOP 1
> ERROR) /data/pdebuyl/reference-code/orac/pre_processing/orac_preproc /data/pdebuyl/reference-code/tsd/MSG3_202308251100/pre/orac_preproc.rk895_8i.driver failed with error code 1. None

Assistance appreciated. I believe that I'm almost there!

**Comment by adamcpovey** [comment]
The error is "you didn't specify a file I want". The reason for that is that `--use_modis_emis` tells ORAC to ignore with RTTOV emissivity atlas (which you have) and only use the MODIS emissivity product (which you do not).

With a little looking around, I believe your problem is that MODIS finally released MYD11C3 officially and so the files we had been using were removed from the internet. Someone will need to spend some time to work out what was done, what we need, and if it can be opened.

Regardless, I would have recommended using the CAMEL surface emissivity product. It was added after I wrote that Wiki page. I also didn't download the data so I've no idea where it comes from and 4pm on Friday of my last day before Xmas is not the time to find out.

**Comment by pdebuyl** [comment]
Thanks @adamcpovey for the reply! I'll check the CAMEL product but in the mean time have happy end-of-year holidays!

**Comment by simonrp84** [comment]
The camel files are distributed with rttov. On my phone so can't find them now but check the rttov downloads page for the emissivity atlas.
Can look into it further next week

**Comment by pdebuyl** [comment]
Hi all,

There seems to be progress. Would one of you be kind enough to send me the files MSG_000E_LSM.nc and MSG_000E_ANGLES.nc ?

(i hope re-asking here instead of opening an issue is fine)

**Comment by pdebuyl** [comment]
BTW: it might not be that file that I am missing sorry

**Comment by pdebuyl** [comment]
For info: installing libemos "manually" installs the data tables (including land-sea-mask) which the ubuntu package called `libemos-data` does not.

**Comment by simonrp84** [comment]
The `MSG_000E_LSM.nc` and `MSG_000E_ANGLES.nc` files are ones I produced manually. Unfortunately I don't have access to them any more...but maybe someone else does.

In any case, they are not mandatory for processing and I only made them to speed things up a bit (rather than calculating LSM + angles for each timeslot). You should be able to run ORAC without these files, although I have no idea how that works with @adamcpovey's python scripts.

**Comment by pdebuyl** [comment]
Thanks Simon :-)

Actually, I was looking at the LSM files because the error message mentioned them. But the issue was that the libemos data files were missing (also with LSM in the name) and now I have those working.

I think I can safely close this issue.

**Comment by simonrp84** [comment]
Glad you got past the error. Fine to close this, but as a general note to the developers it would be good to make these files available to users somehow. they're all on JASMIN.
